---
title: "Overview of Mathematical Functions in R"
output: pdf_document
geometry: margin = 0.8in
author: Julius Kittler
date: September 22, 2019
---
  
  
```{r setup, include=FALSE}

# Set up general options ------------------------------------------------------

knitr::opts_chunk$set(echo = FALSE, fig.height = 8, fig.width = 7, 
                      message = FALSE, warning = FALSE)
options(scipen=999)

```

```{r}

# Plot functions --------------------------------------------------------------

par(mfrow=c(5,2), mar=c(2,2,2,2))
curve(x+0, from = -10, to = 10, main = "x")
curve(abs(x), from = -10, to = 10, main = "|x|")
curve(x^2, from = -10, to = 10, main = "x^2")
curve(x^3, from = -10, to = 10, main = "x^3")
curve(x^4, from = -10, to = 10, main = "x^4")
curve(x^5, from = -10, to = 10, main = "x^5")
curve(x^(1/2), from = -10, to = 10, main = "x^(1/2)")
curve(x^(1/3), from = -10, to = 10, main = "x^(1/3)")
curve(1/x, from = -10, to = 10, main = "1/x")
curve(1/(x^2), from = -10, to = 10, main = "1/(x^2)")

par(mfrow=c(5,2), mar=c(2,2,2,2))
curve(factorial(x), from = -10, to = 10, main = "x!")
curve(2^x, from = -10, to = 10, main = "2^x")
curve(1/sqrt(x), from = -10, to = 10, main = "1/x^(1/2)")
curve(exp(-x), from = -10, to = 10, main = "e^(-x)")
curve(log(x), from = -10, to = 10, main = "ln(x)")
curve(exp(x), from = -10, to = 10, main = "e^x")
curve(log2(x), from = -10, to = 10, main = "log2(x)")
curve(log10(x), from = -10, to = 10, main = "log10(x)")
curve(x*log(x), from = -10, to = 10, main = "x*ln(x)")
curve(log(x)^2, from = -10, to = 10, main = "ln(x)^2")

par(mfrow=c(5,2), mar=c(2,2,2,2))
curve(1 / (1 + exp(-x)), from = -10, to = 10, main = "sigmoid(x)")
curve(10 / (1 + exp(-x)), from = -10, to = 10, main = "10*sigmoid(x)")
curve(tanh(x), from = -10, to = 10, main = "tanh(x)")
curve(exp(x) / sum(exp(x)), from = -10, to = 10, main = "softmax(x)")
curve(pmax(0, x), from = -10, to = 10, main = "rectifier(x)")
curve(log(1 + exp(x)), from = -10, to = 10, main = "softplus(x)")
curve(sign(x), from = -10, to = 10, main = "sign(x)")
curve(floor(x), from = -10, to = 10, main = "floor(x)")
curve(round(x), from = -10, to = 10, main = "round(x)")
curve(ceiling(x), from = -10, to = 10, main = "ceiling(x)")

```

```{r}
par(mfrow=c(5,2), mar=c(2,2,2,2))
curve(sin(x), from = -10, to = 10, main = "sin(x)")
curve(sinpi(x), from = -10, to = 10, main = "sin(pi*x)")
curve(sinh(x), from = -10, to = 10, main = "sinh(x)")
curve(asinh(x), from = -10, to = 10, main = "asinh(x)")
curve(cos(x), from = -10, to = 10, main = "cos(x)")
curve(cospi(x), from = -10, to = 10, main = "cos(pi*x)")
curve(cosh(x), from = -10, to = 10, main = "cosh(x)")
curve(acosh(x), from = -10, to = 10, main = "acosh(x)")
curve(tan(x), from = -10, to = 10, main = "tan(x)")
curve(tanpi(x), from = -10, to = 10, main = "tan(pi*x)")
```

```{r eval = FALSE}

# Other (not included) ---------------------------------------------------------

maxVal = 100
curve((maxVal - x * (x/maxVal)^3)/maxVal, from = 0, to = maxVal)

curve(log(x/(1-x)), from = 0, to = 1, main = "logit(x)") # logit = inv. of sigmoid
curve(1 / (1 + exp(-log(x/(1-x)))), from = 0, to = 1, main = "sigmoid(logit(x))")

curve(x^(1/4), from = -10, to = 10, main = "x^(1/4)")
curve(x^(1/5), from = -10, to = 10, main = "x^(1/5)")

curve(exp(x^2), from = -10, to = 10, main = "e^(x^2)")
curve(exp(sqrt(x)), from = -10, to = 10, main = "e^(sqrt(x))")
curve(1/x^(1/3), from = -10, to = 10, main = "1/x^(1/3)")

curve(tanh(x), from = -10, to = 10, main = "tanh(x)")
curve(atanh(x), from = -10, to = 10, main = "atanh(x)")

```

\newpage  

# Appendix

```{r, ref.label = knitr::all_labels(), echo = TRUE, eval = FALSE}

```